In [18]:
import numpy as np

arr = np.arange(24)
print(type(arr), arr.shape, arr.size, arr.dtype)

arr = arr.reshape(3,4,2)
print(type(arr), arr.shape, arr.size, arr.dtype)

arr.ndim

print(arr.sum(axis=0))
print()
print(arr)

<class 'numpy.ndarray'> (24,) 24 int32
<class 'numpy.ndarray'> (3, 4, 2) 24 int32
[[24 27]
 [30 33]
 [36 39]
 [42 45]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [20]:
a_list = [1.0,2.0,3.0]
print(type(a_list))
arr_list = np.array(a_list)
type(arr_list)

<class 'list'>


numpy.ndarray

In [27]:
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])
x2 = np.array([[1.0, 2.0],[ 3.0, 4.0]]) 
y2 = np.array([[5.0,10.0],[15.0,20.0]]) 
z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

# ndarray basic operation  
print(x1 + y1) 
print(x1 - y1) 
print(x1 * y1) 
print(x1 / y1) 
print(x2 + y2) 
print(x2 * y2)

# ndarray broadcast 
print(x2 + z1) 
print(x2 * z1) 
print(x1 + z2) 
print(x1**2) 
print(x1>=2)

# shape manipulation
print(x2.flatten()) 
print(x2.reshape(2,2))

[ 6. 12. 18.]
[ -4.  -8. -12.]
[ 5. 20. 45.]
[0.2 0.2 0.2]
[[ 6. 12.]
 [18. 24.]]
[[ 5. 20.]
 [45. 80.]]
[[0. 0.]
 [2. 2.]]
[[-1. -4.]
 [-3. -8.]]
[[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
[1. 4. 9.]
[False  True  True]

[[1. 2.]
 [3. 4.]]
[-1. -2.]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [41]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라
print("3의 배수", x[x%3==0])
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
print("4로 나누면 1이 남는 수", x[x%4==1])
# 이 배열에서 3으로 나누면 나눠지고 4로 나누면 1이 남는수를 찾아라

a_arr = list(np.array([x%3==0]&np.array([x%4==1])))
print("3으로 나누면 나눠지고 4로 나누면 1이 남는수", x[a_arr] )


3의 배수 [ 3  6  9 12 15 18]
4로 나누면 1이 남는 수 [ 1  5  9 13 17]
3으로 나누면 나눠지고 4로 나누면 1이 남는수 [9]


<ipython-input-41-496f665db507>:11: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print("3으로 나누면 나눠지고 4로 나누면 1이 남는수", x[a_arr] )
