In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish

Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

In [3]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

In [4]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
fish_input, fish_target)

In [6]:
bream_smelt_ind = ((train_target == "Bream")|(train_target == "smelt"))

train_bream_smelt = train_input[bream_smelt_ind]
target_bream_smelt = train_target[bream_smelt_ind]

In [7]:
print(train_bream_smelt.shape)
print(target_bream_smelt.shape)

(24, 5)
(24,)


In [8]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [14]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.7563025210084033
0.975


In [16]:
print(lr.predict(test_scaled[:10]))
print(test_target[:10])

['Parkki' 'Perch' 'Bream' 'Perch' 'Perch' 'Bream' 'Parkki' 'Bream' 'Bream'
 'Perch']
['Parkki' 'Perch' 'Bream' 'Perch' 'Perch' 'Bream' 'Parkki' 'Bream' 'Bream'
 'Perch']


In [21]:
prob = lr.predict_proba(test_scaled[:5])
print(prob.round(3))

[[0.1   0.458 0.151 0.006 0.235 0.009 0.041]
 [0.004 0.102 0.458 0.016 0.314 0.085 0.021]
 [0.861 0.053 0.015 0.006 0.022 0.    0.042]
 [0.014 0.018 0.659 0.034 0.216 0.002 0.056]
 [0.187 0.001 0.487 0.072 0.005 0.    0.248]]


In [26]:
from sklearn.linear_model import SGDClassifier

sg = SGDClassifier(loss = 'log', max_iter = 100)
sg.fit(train_scaled, train_target)
print(sg.score(train_scaled, train_target))
print(sg.score(test_scaled, test_target))

0.7058823529411765
0.875


In [28]:
sg.partial_fit(train_scaled, train_target)

print(sg.score(train_scaled, train_target))
print(sg.score(test_scaled, test_target))

0.7983193277310925
0.875
