In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf

In [13]:
df = pd.read_csv('/content/one_hot_encording_test.csv', names = ['length','width','height','volume','class_name'])

dataset = df.copy()
label_data = dataset.pop('class_name')
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   length  20 non-null     float64
 1   width   20 non-null     float64
 2   height  20 non-null     float64
 3   volume  20 non-null     float64
dtypes: float64(4)
memory usage: 768.0 bytes
None


In [17]:
encorder = LabelEncoder()
encorder.fit(label_data)
Y = encorder.transform(label_data)

print(Y)

[1 1 1 3 3 3 0 2 2 0 1 1 1 3 3 3 0 2 2 0]


In [22]:
Y_encoded = tf.keras.utils.to_categorical(Y)

print(Y_encoded)
print(Y_encoded.shape)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
(20, 4)


In [23]:
one_hot_label = pd.get_dummies(label_data)
print(one_hot_label)

    bus  car  person  truck
0     0    1       0      0
1     0    1       0      0
2     0    1       0      0
3     0    0       0      1
4     0    0       0      1
5     0    0       0      1
6     1    0       0      0
7     0    0       1      0
8     0    0       1      0
9     1    0       0      0
10    0    1       0      0
11    0    1       0      0
12    0    1       0      0
13    0    0       0      1
14    0    0       0      1
15    0    0       0      1
16    1    0       0      0
17    0    0       1      0
18    0    0       1      0
19    1    0       0      0
